
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - routing.lunar.tech
  resources:
  - routingweights
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - routing.lunar.tech
  resources:
  - routingweights/finalizers
  verbs:
  - update
- apiGroups:
  - routing.lunar.tech
  resources:
  - routingweights/status
  verbs:
  - get
  - patch
  - update
