# permissions for end users to view routingweights.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routingweight-viewer-role
rules:
- apiGroups:
  - routing.lunar.tech
  resources:
  - routingweights
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - routing.lunar.tech
  resources:
  - routingweights/status
  verbs:
  - get
