# permissions for end users to edit routingweights.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routingweight-editor-role
rules:
- apiGroups:
  - routing.lunar.tech
  resources:
  - routingweights
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - routing.lunar.tech
  resources:
  - routingweights/status
  verbs:
  - get
